sudo: false
language: c

deploy:
  provider: s3
  access_key_id: AKIAIAVQAXMLLEPM4I5A
  secret_access_key:
    secure: MMu6HLVnsKQmRN98hPjxcALn21UP5rgmrCQt17HC5EQLKR+O/CuTngU3cZoIWIlkQrl1KIBZ5uAFBO5ywtYC8CGUfhZWBjt8IPUNWQRkKmbRYEB06qcybpdVGjt6X2i6E4hWWvThagpczWYZ30isbWBSDRaL8lxMMyEnkMxlCUQ=
  bucket: stackage-travis
  acl: public_read
  skip_cleanup: true
  local_dir: to-travis
  upload-dir: all-cabal-hashes-tool
  on:
    repo: commercialhaskell/all-cabal-hashes-tool
    branch: master

addons:
  apt:
    packages:
    - libgmp-dev

before_install:
# stack
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- stack --no-terminal setup

script:
- mkdir -p to-travis
- stack --no-terminal build --copy-bins --local-bin-path to-travis
- stack --no-terminal test
- bzip2 to-travis/all-cabal-hashes-tool

cache:
  directories:
  - $HOME/.stack
